### ISSUE TITLE
Utilizar cartão já tokenizado

### ISSUE THREAD

**Issue by chrystianpaulino** [edson-nascimento/getnet-php#11]
Olá, Edson. Caso eu salve o token do cartão na minha base de dados, como eu posso passar por parâmetro na transação?
Pois eu registrei o token na base, e daí passei a string como parâmetro, porém recebi o erro: "Getnet\API\Credit::card(): Argument https://github.com/edson-nascimento/getnet-php/pull/1 ($token) must be of type Getnet\API\Token, string given.
Em resumo, gostaria de utilizar um cartão já tokenizado durante a transação pois não desejo registrar o número do cartão do cliente, que é um parâmetro obrigatório na classe Token()

**Comment by edson-nascimento** [comment]
Olá, atualmente não suporta, pois sempre vai tentar gerar um `token` antes de cada transação.
Essa alteração vai de encontro #9, vou tentar tirar um tempo para ver essa questão até o fim do mês.

**Comment by edson-nascimento** [comment]
Adicionado funcionalidade em https://github.com/edson-nascimento/getnet-php/pull/12
Se poder atualizar para a `v2.1.0` testar e dar um feedback agradeço.
