### ISSUE TITLE
Duvida sobre notificação!

### ISSUE THREAD

**Issue by boahost** [edson-nascimento/getnet-php#14]
Bom dia!

Acredito que não seja o tópico correto o meu questionamento, mas somente uma pequena dúvida.

Quando o cliente realizar o pagamento, tanto por pix ou cartão de crédito, eu verifiquei que é necessário cadastrar as URL'S de notificação diretamente na GETNET. Minha dúvida!  A Getnet me repassará esses campos (PIX)

https://SEU_HOST/SEU_SERVICE?payment_type=pix&customer_id=1234987&order_id=DEV-1588877212&payment_id=41f67a08-7831-4e1b-be2b-9432c0a3309c&amount=1234&status=APPROVED&transaction_id=123412341234123&transaction_timestamp=2020-10-11T13%3A43%3A47Z&receiver_psp_name=PSP%20BANCO%20XYZ&receiver_psp_code=4321&receiver_name=jane%20doe&receiver_cnpj=null&receiver_cpf=46304398034&terminal_nsu=123456789

Os campos em GET serão os campos que eles irão me informar, correto? Agora, o PAYMENT_ID é a chave necessária para validação de pagamento? Ou eu posso informar no momento da compra a ORDER_ID ?

**Comment by edson-nascimento** [comment]
É opcional cadastrar url de notificação para transações de cartão de crédito , mas para o PIX sim é  obrigatório.

Quanto ao `payment_id` ele é um identificador único gerado para cada transação pela **getnet** e é através dele que você pode capturar e cancelar os pagamentos, você não pode informar ele manualmente pois ele é exclusivo da adquirente.

Se ainda estiver com dúvida eles sempre respondem no e-mail [suporte.edigital@getnet.com.br](mailto:suporte.edigital@getnet.com.br)

https://developers.getnet.com.br/api#tag/Notificacoes-1.1
