### ISSUE TITLE
DUVIDA: Consulta sobre Relatórios de Vendas na Biblioteca getnet-php

### ISSUE THREAD

**Issue by thisiscleverson** [edson-nascimento/getnet-php#20]
Olá,

Espero que esta mensagem o encontre bem.

Gostaria de saber se a biblioteca getnet-php possui a capacidade de gerar relatórios de vendas para transações realizadas através da maquininha de cartão. Você poderia fornecer mais detalhes sobre essa funcionalidade?

Obrigado pela sua ajuda.

**Comment by edson-nascimento** [comment]
Olá
Está sdk serve apenas para transações realizadas no ambiente E-Commerce, não server para transações da maquininha de cartão.
Recomendo que entre em contato com a getnet para tirar dúvidas.
