### ISSUE TITLE
Integração em um mvp

### ISSUE THREAD

**Issue by davireimannrossini** [edson-nascimento/getnet-php#22]
Bom Dia, tudo Bem?

Preciso integrar esse código em uma página php, seria possível? Tentei utilizar com minhas credenciais de teste, mas não funcionou. Consegue me dar uma consultoria?
Obrigado

**Comment by edson-nascimento** [comment]
Olá

Sim é possível utilizar essa sdk em projetos `PHP ^8.2` utilizando o `composer` conforme descrito no [README](https://github.com/edson-nascimento/getnet-php/blob/master/Readme.md).

Só vou consigo ajudar se for referente a algum problema/erro na sdk e você não passou nenhum detalhe adicional, mas seu problema pode estar relacionado a instabilidades no ambiente `sandbox`, até o portal dos desenvolvedores https://developers.getnet.com.br/ já está fora a algum tempo.

**Comment by davireimannrossini** [comment]
Na realidade eu criei todo o front com o forms, seleção de tipo de pagamento, preciso tentar entender como integrar com o forms. A parte do forms se quiser acho que da até para contribuir com o projeto. Realmente eles falaram que o sandbox foi  descontinuado, agora somente o ambiente de homologação.

![image](https://github.com/user-attachments/assets/f739ac8a-63f4-4b58-bdbd-f24b0a62a54b)

**Comment by edson-nascimento** [comment]
Talvez no seu caso seja melhor utilizar a solução **[Checkout Iframe](https://developers.getnet.com.br/checkout)**  ao invés dessa sdk, mas o doc deles está off, sugiro entrar em contato com o suporte.
