### ISSUE TITLE
Adicionar Gerenciamento do Cofre

### ISSUE THREAD

**Issue by fhariano** [edson-nascimento/getnet-php#9]
Olá Edson e demais devs.
Poderiam se possível incluir na API o processo de salvamento de cartão de crédito (COFRE) e resgate por ID_CARD e/ou CUSTOMER_ID?
Acredito que essas funcionalidades sejam bem utéis para usarmos em apps salvando o CARD do lado da operadora e não no próprio backend.

Agradeço o excelente trabalho de vocês, parabéns!

Att.,

Flávio Ariano

**Comment by chrystianpaulino** [comment]
Olá, Edson. Caso eu salve o token do cartão na minha base de dados, como eu posso passar por parametro na transacão? Pois eu registrei o token na base, e daí passei a string como parâmetro, porém recebi o erro: "Getnet\\API\\Credit::card(): Argument #1 ($token) must be of type Getnet\\API\\Token, string given

**Comment by edson-nascimento** [comment]
Adicionado funcionalidade em https://github.com/edson-nascimento/getnet-php/pull/12
Se poder atualizar para a `v2.1.0` testar e dar um feedback agradeço.
